In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews =['nice food',
         'amazing restaurant',
         'too good',
         'just loved it!',
         'will go again',
         'horrible food',
         'never go there',
         'poor service',
         'poor quality',
         'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
#ONE HOT TAKE THE REVIEW AS AND VPCABULARY SIZE AS PARAMETHERS
one_hot('amazing restaurant', 50)

[40, 42]

In [6]:
vocab_size = 50
encoded_reviews = [one_hot(b,vocab_size) for b in reviews]
encoded_reviews

[[45, 4],
 [40, 42],
 [44, 25],
 [42, 25, 1],
 [27, 24, 16],
 [10, 4],
 [29, 24, 38],
 [15, 30],
 [15, 22],
 [9, 3]]

In [7]:
max_length = 3
padded_reviews =pad_sequences(encoded_reviews, maxlen = max_length, padding= "post")
padded_reviews

array([[45,  4,  0],
       [40, 42,  0],
       [44, 25,  0],
       [42, 25,  1],
       [27, 24, 16],
       [10,  4,  0],
       [29, 24, 38],
       [15, 30,  0],
       [15, 22,  0],
       [ 9,  3,  0]])

In [8]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [9]:
X = padded_reviews
y = sentiment

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              250       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 266
Trainable params: 266
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
model.fit(X, y, epochs=50, verbose=0)

In [12]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy


1/1 [==============================] - 1s 727ms/step - loss: 0.5938 - accuracy: 1.0000


1.0

In [13]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [17]:
weights[45]

array([ 0.02450406,  0.07286929, -0.09246843,  0.08156855,  0.08825406],
      dtype=float32)

In [18]:
weights[40]

array([ 0.09795304,  0.04590991, -0.08381775,  0.02245083,  0.06917708],
      dtype=float32)

In [16]:
weights[16]

array([ 0.00533889, -0.0984982 , -0.09487998,  0.01001177, -0.02940719],
      dtype=float32)